### ISSUE TITLE
SRS Problem Description confusion

### ISSUE THREAD

**Issue by bmaclach** [PeaWagon/Kaplan#10]
After reading the SRS, I'm not entirely sure about the purpose of Kaplan. I understand that it finds a set of conformers for a molecule, but what makes one potential set of conformers a "better fit" than another? My best guess is that the "best fit" set of conformers are the conformers that are most likely to actually occur in nature. If this is correct, it should be explicitly stated, and I think the Problem Description section 5.1 is the place to do that.

It may also be that if I had all of the characteristics of the intended reader, I would have understood this even without it being explicitly mentioned, in which case it might not be necessary to add anything (though I still think it couldn't hurt).

**Comment by PeaWagon** [comment]
I added a bit more explanation to the problem description 249c7d2
