### ISSUE TITLE
SRS Requirements questions

### ISSUE THREAD

**Issue by bmaclach** [PeaWagon/Kaplan#11]
For the Requirements section, I have the following comments/questions:

- R1 - A lot of the information in the block of text is echoed in the subsequent table and can be removed to avoid redundancy. Also, the sentence beginning with "For example," seems unnecessary (I'm not sure how it relates to Kaplan)
- R2 - My interpretation of this sentence is that the number of dihedral angles is equal to the number of conformers, but my understanding of the science leads to me to believe that my interpretation is wrong, because a single conformer would have many dihedral angles. If this is correct, then this requirement should be rephrased to be less ambiguous.
![image](https://user-images.githubusercontent.com/18634568/46682634-1156ee00-cbbc-11e8-9bce-76fe57df1186.png)
- R5 - What if the input format was not an xyz geometry? If the input was, for example, Z-matrix format, would the output still be in xyz coordinates? Also, if this is a requirement for the output, I think there should be a verb to make that action clear (ex. convert to xyz coordinates _and display them_)
![image](https://user-images.githubusercontent.com/18634568/46682785-87f3eb80-cbbc-11e8-8b26-662d065ccadc.png)
- Kaplan outputs more than just the xyz geometry of the conformers, it also outputs the energy of each conformer. There should be a requirement for this.
- Could new functional requirements be added to address any nonfunctional requirements? An example that pops out to me is the nonfunctional requirement "The program should have suggestions for inputs to help the user get started" which could be easily mapped to a functional requirement for providing those suggestions.

**Comment by PeaWagon** [comment]
Should be fixed 249c7d2
