### ISSUE TITLE
SRS Goal Statements questions

### ISSUE THREAD

**Issue by bmaclach** [PeaWagon/Kaplan#12]
With regards to the Goal Statements, I have the following questions/comments:

- In GS1, I do not think the "Alternatively," sentence is necessary. That information will be made clear with the refinement to the instance model.
- I would argue that there is a 2nd goal here, which is to determine the energy of each conformer. The energy values are one of Kaplan's outputs so it makes sense to me that their determination must be one of the goals.

**Comment by PeaWagon** [comment]
I now have two goal statements. I will update the traceability tables later. For now here is the fix 249c7d2
