### ISSUE TITLE
SRS Completeness issues

### ISSUE THREAD

**Issue by bmaclach** [PeaWagon/Kaplan#13]
The following (mostly minor issues) were missing from the SRS:

- Content in section 5.2.7 Properties of a Correct Solution
- Exhaustive symbol descriptions in GD1 (for example, include a definition for _z_.)
- The left-hand sides of the equations in DD1 and DD2
- In section 3.4 Organization of Document, descriptions for sections after section 4

**Comment by PeaWagon** [comment]
I added more to these sections here 249c7d2
