### ISSUE TITLE
SystVnV plan first draft

### ISSUE THREAD

**Issue by PeaWagon** [PeaWagon/Kaplan#14]
Please see commit 6d2e04cdb8b4dfea52b7cdd56be1474435e0c680

**Comment by vajihehm** [comment]
@smiths @PeaWagon Dr.Smith and Jenifer I apologize for the late submission the issues and hope that it is not too late. Thanks.

**Comment by smiths** [comment]
@PeaWagon, my comments on your Sys VnV plan are given in commit ae78640.
