### ISSUE TITLE
SysVnVPlan VnV team issue

### ISSUE THREAD

**Issue by vajihehm** [PeaWagon/Kaplan#16]
@PeaWagon In the section  4.1 - Verification and Validation Team, It must use written English language not French;). Please change it.

**Comment by PeaWagon** [comment]
Lol inside jokes are allowed. Besides, je suis canadienne :wink: 

https://www.youtube.com/watch?v=FIDModxaJG8

**Comment by smiths** [comment]
Thanks for the joke @PeaWagon, and for the X-files reference.  😄
