### ISSUE TITLE
MG issue #1 - Anticipated changes

### ISSUE THREAD

**Issue by Malavika-Srinivasan** [PeaWagon/Kaplan#25]
@PeaWagon 

Hi Jenn,

Your AC6 says that the software can be changed into a library by incorporating into other software packages. In AC7, you mention that using it on through the phone. I can see a connection between them but, I think it is better to mention that it may be a `mobile application '. 

Malavika

**Comment by PeaWagon** [comment]
I think I got rid of the AC about making my program a library (since @smiths review indicated that ACs are supposed to change one module only). I added your comment that it might be used on a mobile application. It will go in a future commit.

**Comment by PeaWagon** [comment]
Solved bceebbb
