### ISSUE TITLE
MG issue #2 - Unlikely changes

### ISSUE THREAD

**Issue by Malavika-Srinivasan** [PeaWagon/Kaplan#26]
@PeaWagon 

Hi Jenn,

I am not sure if UC3 is needed. If the goal changes, then its not the same software anymore. Can you please elaborate if you see a change in the goal?

Malavika

**Comment by PeaWagon** [comment]
Since UC3 changes every module, I will remove it.

**Comment by PeaWagon** [comment]
Done bceebbb
