### ISSUE TITLE
MG issue #3 - M2

### ISSUE THREAD

**Issue by Malavika-Srinivasan** [PeaWagon/Kaplan#27]
@PeaWagon 

Hi Jenn,

This is my last issue.  :)
It's a well done document.

In the services for M2, you say that M2 `communicates ... to M3'. From your description, I think M3 uses M2 and you don't have to mention it in the reverse way (M2 communicates to M3). Just for clarity, Can you please rewrite this sentence ?

Malavika

**Comment by PeaWagon** [comment]
Okay done in bceebbb
