### ISSUE TITLE
Sorry 

### ISSUE THREAD

**Issue by Malavika-Srinivasan** [PeaWagon/Kaplan#31]
@PeaWagon @smiths 

Hi Jen, 

I am writing this here because I don't have your email. I posted issues in your MG instead of Vajiheh's MG. I referred the excel sheet but wrongly interpreted it. Sorry again.

Malavika

**Comment by PeaWagon** [comment]
Email: garnej2 AT mcmaster DOT ca No worries :P I don't mind more feedback.
