### ISSUE TITLE
First draft of unit vnv plan

### ISSUE THREAD

**Issue by PeaWagon** [PeaWagon/Kaplan#36]
See commit 104d1506a1f58a21e9e9edd975f5bc07cd9ea97c

:+1:

**Comment by smiths** [comment]
Thank you.  I look forward to reviewing it.

**Comment by smiths** [comment]
@PeaWagon I have added a few comments to your unit vnv plan at 7846fb2.

I apologize for the delay in the review.  You don't need to worry about making any changes to your final documentation.  Your vnv plan looks good.
