### ISSUE TITLE
SRS first draft

### ISSUE THREAD

**Issue by PeaWagon** [PeaWagon/Kaplan#4]
4217c80d6dcca41c8db925d21b6d7a771e5ecd2b

**Comment by smiths** [comment]
Thank you @PeaWagon  I look forward to reviewing your SRS.  😄

**Comment by smiths** [comment]
Some initial comments are included in commit 2465957.

**Comment by smiths** [comment]
@PeaWagon, I have completed my review of your SRS.  My comments are embedded in your tex file (11b5809).
