### ISSUE TITLE
SRS typos and other minor consistency errors

### ISSUE THREAD

**Issue by bmaclach** [PeaWagon/Kaplan#5]
The following is a list of typos and other minor consistency issues with the current draft of the SRS:

- In section 3, in the 2nd sentence, "moleule" should be "molecule"
- In section 3, 3rd sentence, "abbreivated" should be "abbreviated"
- In section 3, 4th sentence, "geometies" should be "geometries"
- In section 3, 4th sentence, "procurring" should be "procuring"
- In section 3.2, 3rd sentence, "diehdral" should be "dihedral"
- In section 3.3, in the itemized list, "hamiltonian" should be capitalized
- In section 3.4, 2nd sentence, there is a reference to section 1 but this should be a reference to section 2
- In section 4.1, the first paragraph should not be indented (to be consistent with the rest of the document)
- In section 4.1, 2nd sentence, "includes" should be "include"
- In section 4.1, the 2nd item of the User Responsibilities list should not end in a period (for consistency)
- In section 4.2, "first year" should be "first-year" (for consistency with rest of document)
- In section 4.2, "3rd year" should be "third-year" (for consistency with rest of document)
- In section 5.1.2, item PS1, first sentence, "molecule" should be capitalized
- In section 5.1.2, Figure 3 appears without any corresponding reference in the text to give it context
- In section 5.2.1, A5, the word "a" is missing before "linear combination"
- In section 5.2.5, 2nd paragraph, 3rd sentence is written imperatively (should be rephrased with a clear subject of the sentence -- what is manipulating the dihedral angles to solve for _Fit_G_?)
- In section 5.2.5, IM1 description, I do not think the words "water temperature" were intended to be there
- In section 5.2.5, IM1 description, "1" should be "one" (for consistency)
- In section 5.2.6, Table 2, an asterisk should appear next to the table entry for G_n (as it is referenced by the asterisk note below the table)
- In section 6.1, R1, in the last entry in the table "to specify to connectivity" should be "to specify the connectivity"
- In section 9, T2, "hamiltonian" should be capitalized

**Comment by PeaWagon** [comment]
I fixed everything except the asterisk for table 2 (since it's in the column next to the pertinent variable). 93131d92a2bc7ef1029578ef5c1c8a4ea6d5aa9a
