### ISSUE TITLE
SRS Table of Symbols "Array of..." descriptions

### ISSUE THREAD

**Issue by bmaclach** [PeaWagon/Kaplan#7]
In the Table of Symbols, the descriptions for some symbols (examples below) include phrases such as "array of length 3", which sounds like an implementation detail.

![image](https://user-images.githubusercontent.com/18634568/46680585-680df900-cbb7-11e8-8a41-78ebe5fb2da1.png)

These could be rephrased to something along the lines of "position of electron in Cartesian coordinates" to be more abstract.

**Comment by PeaWagon** [comment]
417f8ef
