### ISSUE TITLE
SRS Use of "SI Units" even when units are not SI

### ISSUE THREAD

**Issue by bmaclach** [PeaWagon/Kaplan#8]
In the Table of Units there is an "SI" column, and the text claims that SI is used throughout.

![image](https://user-images.githubusercontent.com/18634568/46681053-6a248780-cbb8-11e8-8709-d75928e87965.png)

Also in the GDs and DDs there is a row heading "SI Units". 

![image](https://user-images.githubusercontent.com/18634568/46681174-a48e2480-cbb8-11e8-995c-c4e22552847c.png)

Angstroms are not SI units, so in this case I think these heading names should be changed to not specify "SI".

**Comment by PeaWagon** [comment]
Fixed in fbc963389063b7078eb552416922cc54027961e4
