### ISSUE TITLE
SRS Traceability issues

### ISSUE THREAD

**Issue by bmaclach** [PeaWagon/Kaplan#9]
Some traceability information is missing from the SRS:

- In the Assumptions section, Likely Changes should be referenced in square brackets next to their respective assumptions
- In the Likely Changes section, the assumption reference should be more clear (wrap it in square brackets or explicitly reference it in the sentence)
- In the traceability matrix Table 5, A3 should be referenced by IM1
- In the traceability matrix Table 7, R4 and R5 should be referenced by something (can include the data constraints section as a column in order to achieve this, see SWHS for example of this)
- In the traceability matrix Table 6, I do not think there should be an X in the DD1 column, T1 row (If DD1 were changed would Schrodingers equation also need to change? I'm not entirely sure about this one)

**Comment by PeaWagon** [comment]
417f8ef
